// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: squareup/gap-admin-playground/service.proto

package service

import (
	context "context"
)
